name: plugin_sdk
description: SDK for developing Plugins Platform plugins.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../plugins_platform/packages/core
  stac_renderer:
    path: ../plugins_platform/packages/stac_renderer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
