#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ENTRY_FILE = ROOT / "src" / "index.js"
BUNDLE_FILE = ROOT / "dist" / "bundle.js"
MANIFEST_FILE = ROOT / "manifest.json"
RUNTIME_EXPORTS = [
    "onActivate",
    "onDeactivate",
    "discoverFeeds",
    "getFeedInfo",
    "refresh",
    "loadMore",
    "getArticleDetail",
]


def main() -> int:
    source = ENTRY_FILE.read_text(encoding="utf-8")
    source = re.sub(r"^\s*export\s+async\s+function\s+", "async function ", source, flags=re.MULTILINE)
    source = re.sub(r"^\s*export\s+function\s+", "function ", source, flags=re.MULTILINE)
    bundle = render_bundle(source)

    BUNDLE_FILE.parent.mkdir(parents=True, exist_ok=True)
    BUNDLE_FILE.write_text(bundle, encoding="utf-8")

    manifest = json.loads(MANIFEST_FILE.read_text(encoding="utf-8"))
    manifest["engine"]["bundle"] = "dist/bundle.js"
    manifest["engine"]["bundleSize"] = len(bundle.encode("utf-8"))
    manifest["engine"]["bundleHash"] = sha256(bundle)
    MANIFEST_FILE.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(
        f"Built {BUNDLE_FILE.relative_to(ROOT)} "
        f"({len(bundle.encode('utf-8'))} bytes, sha256 {sha256(bundle)})"
    )
    return 0


def render_bundle(source: str) -> str:
    lines = [
        "// AI news daily plugin runtime bundle.",
        "// Generated from src/index.js. Do not edit this file by hand.",
        "(function(globalThis) {",
    ]
    for line in source.splitlines():
        lines.append(f"  {line}")
    lines.append("")
    for name in RUNTIME_EXPORTS:
        lines.append(f"  globalThis.{name} = {name};")
    lines.append("})(globalThis);")
    lines.append("")
    return "\n".join(lines)


def sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


if __name__ == "__main__":
    raise SystemExit(main())
